# Generated by Django 5.2.1 on 2025-05-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('STATUS_NEW', 'new'), ('STATUS_USED', 'used')], default='STATUS_USED'),
        ),
    ]
