# Generated by Django 5.2.1 on 2025-05-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_advertisement_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sender', models.PositiveIntegerField(verbose_name='Номер инициатора предложения')),
                ('num_ads_sender', models.PositiveIntegerField(verbose_name='Номер принимающего предложения')),
                ('comment', models.CharField(max_length=350, verbose_name='Комментраий')),
                ('status', models.CharField(choices=[('waiting', 'wtg'), ('accepted', 'accpt')], default='waiting')),
            ],
        ),
    ]
