# Generated by Django 5.2.1 on 2025-05-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_proposal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proposal',
            new_name='ExchangeProposal',
        ),
    ]
