# Generated by Django 5.2.1 on 2025-05-23 11:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_rename_proposal_exchangeproposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeproposal',
            name='num_ads_sender',
        ),
        migrations.RemoveField(
            model_name='exchangeproposal',
            name='num_sender',
        ),
        migrations.AddField(
            model_name='exchangeproposal',
            name='ad_receiver',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user_receiver', to='ads.advertisement', verbose_name='Номер принимающего предложения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangeproposal',
            name='ad_sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_sender', to='ads.advertisement', verbose_name='Номер инициатора предложения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangeproposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
