# Generated by Django 5.2.1 on 2025-05-23 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_remove_exchangeproposal_num_ads_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='ads.advertisement', verbose_name='Номер принимающего предложения'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='ads.advertisement', verbose_name='Номер инициатора предложения'),
        ),
    ]
