# Generated by Django 5.2.1 on 2025-05-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_alter_exchangeproposal_ad_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='waiting'),
        ),
    ]
