# Generated by Django 5.2.1 on 2025-05-23 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_alter_exchangeproposal_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeproposal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customuser', to=settings.AUTH_USER_MODEL, verbose_name='Номер инициатора предложения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='ads.advertisement', verbose_name='Номер объявления принимающего предложения'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='ads.advertisement', verbose_name='Номер объявления инициатора предложения'),
        ),
    ]
